### ISSUE TITLE
我怀疑是大佬故意留的坑。。。

### ISSUE THREAD

**Issue by dchaofei** [elarity/data-structure-php-clanguage#3]
比如`7. 数据结构之队列`里的 pop 函数。: )

**Comment by elarity** [comment]
忘了加return了，不是坑，是我自己状态不好晕头了，thx！这么明显的错误，为啥不提PR。

**Comment by elarity** [comment]
别的问题也没看出来，是不是return的问题？

**Comment by dchaofei** [comment]
@elarity 我也是正在努力的泥腿子程序员，看你前边所说的队列是先入先出，那么 `pop()` 是不是应该这样写, 把 `$length - 1` 换成 `0`
```php
public function pop(){
        $this->delete_item( 0 );
      }
```

**Comment by elarity** [comment]
看来那天面试导致的状态确实不好。
除了你刚提出的问题，队列这一篇章有些其他问题，两个方法的名称我需要修改一下：
在队列头部移除一个元素叫做shift
在队列尾巴添加一个元素叫做pop

非常感谢！不然会给其他同学带来很大的误导！

**Comment by elarity** [comment]
。。。。 。。。
完了，我彻底晕了，comment也能comment错
看来那天面试导致的状态确实不好。
除了你刚提出的问题，队列这一篇章有些其他问题，两个方法的名称我需要修改一下：
**_## 在队列头部移除一个元素叫做shift
在队列尾巴添加一个元素叫做push_**

非常感谢！不然会给其他同学带来很大的误导！

**Comment by dchaofei** [comment]
没事，小错误而已，前几天看到你的博客，发现篇篇都是精品，甚是仰慕。

**Comment by elarity** [comment]
篇篇精品？这两天我就给你水两篇，让你感受一下水的最高境界。
